services:
  - type: web
    name: rail-backend
    env: python
    buildCommand: "pip install fastapi uvicorn[standard] gunicorn SQLAlchemy aiosqlite python-dotenv orjson python-jose ecdsa pyasn1 passlib[bcrypt] redis websockets python-multipart --no-cache-dir"
    startCommand: "cd backend && gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:$PORT app.main:app"
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENV
        value: prod
      - key: DB_TYPE
        value: sqlite
      - key: SQLITE_PATH
        value: /tmp/rail.db


